language: python
matrix:
  include:
    - name: 'Python 3.7.4 on Xenial Linux'
      python:
        - '3.7.4'
    - name: 'Python 3.7.4 on macOS'
      os: osx
      osx_image: xcode11.2  # macOS has python2 & python3 by default
      language: shell
    - name: 'Python 3.7.4 on Windows'
      os: windows
      filter_secrets: false
      language: shell
      before_install:
        - choco install python --version 3.7.4  # no command python3 will be create
        - choco install nsis -y
        - python -m pip install --upgrade pip
      env: PATH="/c/Program Files (x86)/NSIS/:/c/Program Files/NSIS/:/c/Python37:/c/Python37/Scripts:$PATH"

install:
  - pip3 install -r requirements.txt

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python3 setup.py -t build
      zip -q -r dist/nice-you-get-$TRAVIS_OS_NAME-$TRAVIS_TAG.zip dist/linux/*
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      python3 setup.py -t build
      zip -q -r dist/nice-you-get-$TRAVIS_OS_NAME-$TRAVIS_TAG.zip dist/drawin/*.app
    else
      python setup.py -t build
      makensis -V3 -DPRODUCT_VERSION='$TRAVIS_TAG' script.nsi
      7z a dist/nice-you-get-$TRAVIS_OS_NAME-$TRAVIS_TAG.zip dist/win32/*
    fi
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file:
    - 'dist/*.zip'
    - 'dist/*.exe'
  api_key: ${GH_TOKEN}
  on:
    repo: wuyue92tree/nice-you-get
    tags: true
    all_branches: true
branches:
  except:
    - develop
    - master